---
dist: bionic
language: python
python:
  - "3.8"

before_install:
  - sudo apt-get update

env:
  global:
    - ROLE_NAME: aviconfig
  matrix:
    - MOLECULE_DISTRO: ubuntu:16.04
services:
  - docker

install:
  - pip install ansible molecule docker pluggy==0.13.1 yamllint ansible-lint docker molecule-docker

before_script:
  - cd ../
  - export DEFAULT_ROLES_PATH=/home/travis/avinetworks/avinetworks.aviconfig/molecule/default/roles:/home/travis/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/travis/avinetworks/avinetworks.aviconfig/molecule/default
  - export ANSIBLE_ROLES_PATH=$DEFAULT_ROLES_PATH:/home/travis/.cache/molecule/avinetworks.aviconfig/default/roles/
  - mv ansible-role-$ROLE_NAME avinetworks.$ROLE_NAME
  - cd avinetworks.$ROLE_NAME

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    recipients:
      - rastogiga@vmware.com
      - deshpandech@vmware.com
      - pshrikan@vmware.com
      - sabandi@vmware.com
      - samol@vmware.com
    on_failure: always
