---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint tasks -c molecule/default/.yamllint
  ansible-lint converge.yml
platforms:
  - name:  instances
    image: ${MOLECULE_DISTRO:-ubuntu:16.04}
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
